#!/usr/bin/env node
const yargs = require('yargs');
const dailyCommand = require('./src/command/daily');
const upcomingCommand = require('./src/command/upcoming');
require('dotenv').config();

yargs
  .usage('$0 <cmd> [args]')
  .command('daily', 'Send daily summary',
    (yargs) => {
        yargs.positional('name', {
            type: 'string',
            default: 'Cambi',
            describe: 'the name to say hello to'
        });
    },
    (argv) => dailyCommand(argv)
  )
  .command('upcoming [minutes]', 'Publish upcoming events',
      (yargs) => {
          yargs.positional('minutes', {
              type: 'number',
              default: '60',
              describe: 'Number of minutes'
          });
      },
      (argv) => upcomingCommand(argv)
  )
  .help()
  .argv;
