#!/usr/bin/env node
const yargs = require('yargs');
const dailyCommand = require('./src/command/daily');
const upcomingCommand = require('./src/command/upcoming');
const calendarCommand = require('./src/command/calendar');
const weekCalendarCommand = require('./src/command/week-calendar');
require('dotenv').config();

yargs
  .usage('$0 <cmd> [args]')
  .command('daily', 'Send daily summary',
    (yargs) => {},
    (argv) => dailyCommand(argv)
  )
  .command('calendar', 'Send month emoji calendar',
      (yargs) => {},
      (argv) => calendarCommand(argv)
  )
  .command('week-calendar', 'Send week emoji calendar',
      (yargs) => {},
      (argv) => weekCalendarCommand(argv)
  )
  .command('upcoming [minutes]', 'Publish upcoming events',
      (yargs) => {
          yargs.positional('minutes', {
              type: 'number',
              default: '60',
              describe: 'Number of minutes'
          });
      },
      (argv) => upcomingCommand(argv)
  )
  .help()
  .argv;
